apiVersion: v1
kind: Service
metadata:
  name: irmgard-webserver
  namespace: irmgard
  labels:
    app.kubernetes.io/name: irmgard-webserver
spec:
  selector:
    app.kubernetes.io/name: irmgard-webserver
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
